version: "3.0"

services:

  auth:
    image: harcastic/auth-service:latest
    container_name: auth-service
    restart: always 
    pull_policy: always
    env_file:
      - ./backend/auth-service/.env
    ports:
      - "5001:5001"

  blog:
    image: harcastic/blog-service:latest
    container_name: blog-service
    restart: always 
    pull_policy: always
    env_file:
      - ./backend/blog-service/.env
    ports:
      - "5002:5002"

  gateway:
    image: harcastic/gateway:latest
    container_name: gateway
    restart: always
    pull_policy: always
    env_file:
      - ./backend/gateway/.env
    ports:
      - "5000:5000"
    depends_on:
      - auth
      - blog

  frontend:
    image: harcastic/frontend:latest
    container_name: frontend
    restart: always
    pull_policy: always
    ports:
      - "3000:3000"
    depends_on:
      - gateway


  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - gateway