name: Build & Push Docker Images

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build & Push Auth Service
      - name: Build & Push Auth
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/auth-service:latest ./backend/auth-service
          docker push ${{ secrets.DOCKER_USERNAME }}/auth-service:latest

      # 4. Blog Service
      - name: Build & Push Blog
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/blog-service:latest ./backend/blog-service
          docker push ${{ secrets.DOCKER_USERNAME }}/blog-service:latest

      # 5. API Gateway
      - name: Build & Push Gateway
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest ./backend/gateway
          docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest

      # 6. Frontend
      - name: Build & Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

      # 4️⃣ Deploy Services to VM One by One (Safe)
      - name: Deploy Auth Service
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd devops-app || exit
            docker pull ${{ secrets.DOCKER_USERNAME }}/auth-service:latest
            docker-compose up -d auth

      - name: Deploy Blog Service
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd devops-app || exit
            docker pull ${{ secrets.DOCKER_USERNAME }}/blog-service:latest
            docker-compose up -d blog

      - name: Deploy API Gateway
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd devops-app || exit
            docker pull ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest
            docker-compose up -d gateway

      - name: Deploy Frontend
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd devops-app || exit
            docker pull ${{ secrets.DOCKER_USERNAME }}/frontend:latest
            docker-compose up -d frontend

      - name: Deploy Nginx
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd devops-app || exit
            docker-compose up -d nginx